export default function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
  
  if (req.method === "OPTIONS") {
    res.status(200).end();
    return;
  }

  res.status(200).json([
    {
      id: 1,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0815.35.png",
      Cod: "9.11.0815.35",
      nome: "Torneira lavatório Mesa CI/JR UP Cuba de Apoio GRAFITE 20cm",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 2,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0814.35.png",
      Cod: "9.11.0814.35",
      nome: "Torneira lavatório Mesa CI/JR Cuba de Apoio GRAFITE 24cm",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    }
    ,
    {
      id: 3,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0906.35.png",
      Cod: "9.11.0906.35",
      nome: "Torneira lavatório Mesa CI/JR Cuba de Apoio GRAFITE 28cm",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 4,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0907.35.png",
      Cod: "9.11.0907.35",
      nome: "Torneira lavatório Mesa CI/JR UP Real Cuba GRAFITE 24cm",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 5,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0989.35.png",
      Cod: "9.11.0989.35",
      nome: "Torneira lavatório Bella Luna Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 6,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0991.35.png",
      Cod: "9.11.0991.35",
      nome: "Torneira lavatório Bella Luna Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 7,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/9.11.0997.35.png",
      Cod: "9.11.0997.35",
      nome: "Torneira lavatório Clock",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários"
    },
    {
      id: 8,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0504.35.png",
      Cod: "9.01.0504.35",
      nome: "Saboneteira Parede Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 9,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0505.35.png",
      Cod: "9.01.0505.35",
      nome: "Cabide Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 10,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0506.35.png",
      Cod: "9.01.0506.35",
      nome: "Papeleira Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 11,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0508.35.png",
      Cod: "9.01.0508.35",
      nome: "Porta Toalha Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 12,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0512.35.png",
      Cod: "9.01.0512.35",
      nome: "Cabide Duplo Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 13,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0509.35.png",
      Cod: "9.01.0509.35",
      nome: "Porta Toalha Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 14,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acessorios/9.01.0511.35.png",
      Cod: "9.01.0511.35",
      nome: "Porta Shampoo Pieno Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acessorios"
    },
    {
      id: 15,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acabamentos/9.12.0154.35.png",
      Cod: "9.12.0154.355",
      nome: "Acabamento Bela Luna Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acabamentos"
    },
    {
      id: 16,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acabamentos/9.12.0156.35.png",
      Cod: "9.12.0156.35",
      nome: "Acabamento Treviso Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acabamentos"
    },
    {
      id: 17,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Grafite/Acabamentos/9.12.0158.35.png",
      Cod: "9.12.0158.35",
      nome: "Acabamento clock Grafite",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
      categoria: "Acabamentos"
    },
    {
      id: 18,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Monocomando/9.27.0115.18.png",
      Cod: "9.27.0115.18",
      nome: "Monocomando Cozinha Mesa Duo Gourmet com Ducha Extensiva",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
    },
    {
      id: 19,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Monocomando/9.27.0118.18.png",
      Cod: "9.27.0118.18",
      nome: "Monocomando Cozinha Mesa Duo Gourmet com Ducha Extensiva",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
    },
    {
      id: 20,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Monocomando/9.27.0115.25.jpg",
      Cod: "9.27.0117.18",
      nome: "Monocomando Cozinha Mesa Duo Gourmet com Ducha Extensiva",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
    },
    {
      id: 21,
      imagem: "https://forusi-api.vercel.app/img/Metais/Linhas/Monocomando/9.27.0118.25.jpg",
      Cod: "9.27.0118.25",
      nome: "Monocomando Cozinha Mesa Duo Gourmet com Ducha Extensiva",
      descricao: "Descrição do produto.",
      categoria: "Metais Sanitários",
    },
    {
      id: 22,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Prime.png",
      nome: "Ducha Prime",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 23,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Prime-Branca.png",
      nome: "Ducha Prime",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 24,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Essenziali.png",
      nome: "Ducha Essenziali",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 25,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Essenziali-Branca.png",
      nome: "Ducha Essenziali",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 26,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Stilo.png",
      nome: "Ducha Stilo",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 27,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Stilo-branca.png",
      nome: "Ducha Stilo Branca",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 28,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Kit-Ducha-Stilo.png",
      nome: "Kit Ducha Stilo",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 29,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Kit-Ducha-Stilo-Branca.png",
      nome: "Kit Ducha Stilo Branca",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 30,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Braco-de-Chuveiro.png",
      nome: "Braço de Chuveiro",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 31,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Braco-de-Chuveiro-Branco.png",
      nome: "Braço de Chuveiro Bran",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 32,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Resistencia.png",
      nome: "Resistência",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 33,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Resistencia-Prime.png",
      nome: "Resistência Prime",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 34,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Torneira-Attiva-Parede.png",
      nome: "Torneira Attiva Parede",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 35,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Torneira-Attiva-Parede-Branca.png",
      nome: "Torneira Attiva Parede",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 36,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Torneira-Attiva-Mesa.png", 
      nome: "Torneira Attiva Mesa",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 37,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Torneira-Attiva-Mesa-Branca.png",
      nome: "Torneira Attiva Mesa",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 38,
      imagem: "https://forusi-api.vercel.app/img/Ducha/Ducha-Attiva-mesa.png",
      nome: "Ducha Attiva Mesa",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 39,
      imagem: "https://forusi-api.vercel.app/img/Ducha/kit-Chuveirinho.png",
      nome: "Kit Chuveirinho",
      nome: "Acabamento para Ducha",
      descricao: "Descrição do produto.",
      categoria: "Chuveiros e Torneiras Elétricas",
    },
    {
      id: 40,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.60.0091.23.png",
      nome: "Pistola Alta Produção Sucção Profissional ",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 41,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.60.0092.23.png",
      nome: "Pistola de Ar Direto",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 42,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.60.0089.18.png",
      nome: "Pistola Baixa Produção Gravidade",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 43,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.60.0090.22.png",
      nome: "Pistola HVLP Gravidade H827",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 44,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.62.0006.18.png",
      nome: "SL-1 Pistola PP",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 45,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.62.0007.18.png",
      nome: "SL-2 Pistola PP",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 46,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.62.0008.18.png",
      nome: "PVL-3 - Pistola PP",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 47,
      imagem: "https://forusi-api.vercel.app/img/Pistolas/07.9.64.0125.00.png",
      nome: "FOC-600",
      descricao: "Descrição do produto.",
      categoria: "Pistolas para Pintura",
    },
    {
      id: 48,
      imagem: "https://forusi-api.vercel.app/img/Forro/Preto.png",
      nome: "Forro PVC Preto",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 49,
      imagem: "https://forusi-api.vercel.app/img/Forro/Branco.png",
      nome: "Forro PVC Branco",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 50,
      imagem: "https://forusi-api.vercel.app/img/Forro/Amarelo.png",
      nome: "Forro PVC Amarelo",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 51,
      imagem: "https://forusi-api.vercel.app/img/Forro/bege.png",
      nome: "Forro PVC Bege",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 52,
      imagem: "https://forusi-api.vercel.app/img/Forro/Cerejeira.png",
      nome: "Forro PVC Cerejeira",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 53,
      imagem: "https://forusi-api.vercel.app/img/Forro/mogno.png",
      nome: "Forro PVC Mogno",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 54,
      imagem: "https://forusi-api.vercel.app/img/Forro/u.png",
      nome: "Roda forro perfil “u”",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 55,
      imagem: "https://forusi-api.vercel.app/img/Forro/h.png",
      nome: "Emenda perfil “h”",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 56,
      imagem: "https://forusi-api.vercel.app/img/Forro/Canto-externo.png",
      nome: "Canto externo",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 57,
      imagem: "https://forusi-api.vercel.app/img/Forro/Canto-Interno.png",
      nome: "Canto interno",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 58,
      imagem: "https://forusi-api.vercel.app/img/Forro/Moldura-tradicional.png",
      nome: "Moldura tradicional",
      descricao: "Descrição do produto.",
      categoria: "Forros de PVC",
    },
    {
      id: 59,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/filtro-de-linha.png",
      nome: "Filtro de linha",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 60,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/filtro-de-linha-usb.png",
      nome: "Filtro de linha USB",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 61,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/Extensao-Eletrica-2p-t.png",
      nome: "Extensão Elétrica 2P+T",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 62,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/Extensao-Eletrica-2p.png",
      nome: "Extensão Elétrica 2P",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 63,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/filtro-adsl-simples.png",
      nome: "Filtro ADSL Simples",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 64,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/filtro-adsl-duplo.png",
      nome: "Filtro ADSL duplo",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 65,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/Capacitador-de-partida-2fios.png",
      nome: "Capacitador de Partida 2 fios",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 66,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/Capacitador-de-partida-3fios.png",
      nome: "Capacitador para Ventilador 3 fios",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 67,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/fusivel-microondas.png",
      nome: "Fusível Microondas",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 68,
      imagem: "https://forusi-api.vercel.app/img/Materiais-Eletricos/fusivel-de-vidro.png",
      nome: "Fusível de Vidro",
      descricao: "Descrição do produto.",
      categoria: "Materiais Elétricos",
    },
    {
      id: 69,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Conector-Informatica.png",
      nome: "Conector Para Informática",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 70,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Conector-Informatica-180.png",
      nome: "Conector Para Informática 180°",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 71,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Conector-Gravador.png",
      nome: "Conector Para Gravador",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 72,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Conector-Notebook.png",
      nome: "Conector Para Notebook",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 73,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Plugue-2p-180.png",
      nome: "Plugue 2P 180°",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 74,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Plugue-2p-180-pre-isolado.png",
      nome: "Plugue 2P 180° Pré-Isolado",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
    {
      id: 75,
      imagem: "https://forusi-api.vercel.app/img/Plugues-Cabos/Plugue-2p-t180.png",
      nome: "Plugue 2P+T 180°",
      descricao: "Descrição do produto.",
      categoria: "Plugues e Conectores",
    },
  ]);
}
